# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool: Azure Pipelines

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo "Validating quality..."
      displayName: 'Valid Application'
    - script: echo "Building the application..."
      displayName: 'Build Application'
    - script: echo "Running tests..."
      displayName: 'Run Tests'

- stage: DeployTest
  displayName: 'Deploy & Test Stage'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - script: echo "Deploying the application..."
      displayName: 'Deploy Application'
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: echo "Testing the application..."
      displayName: 'Test Application'